### ISSUE TITLE
Cannot install by Gradle

### ISSUE THREAD

**Issue by tuhuynh27** [bigchaindb/java-driver#4]
Run `./gradlew install` and it said:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find org.interledger:java-crypto-conditions:2.0.0-SNAPSHOT.
  Searched in the following locations:
      http://repo.maven.apache.org/maven2/org/interledger/java-crypto-conditions/2.0.0-SNAPSHOT/maven-metadata.xml
      http://repo.maven.apache.org/maven2/org/interledger/java-crypto-conditions/2.0.0-SNAPSHOT/java-crypto-conditions-2.0.0-SNAPSHOT.pom
      http://repo.maven.apache.org/maven2/org/interledger/java-crypto-conditions/2.0.0-SNAPSHOT/java-crypto-conditions-2.0.0-SNAPSHOT.jar
      file:/root/.m2/repository/org/interledger/java-crypto-conditions/2.0.0-SNAPSHOT/maven-metadata.xml
      file:/root/.m2/repository/org/interledger/java-crypto-conditions/2.0.0-SNAPSHOT/java-crypto-conditions-2.0.0-SNAPSHOT.pom
      file:/root/.m2/repository/org/interledger/java-crypto-conditions/2.0.0-SNAPSHOT/java-crypto-conditions-2.0.0-SNAPSHOT.jar
  Required by:
      com.authenteq:java-bigchaindb-driver:0.1
```

**Comment by ttmc** [comment]
@huynhminhtufu Thanks for reporting this issue. Unfortunately, the Java driver doesn't currently have anyone maintaining it, so I don't know when this issue will get resolved.

If you are able to resolve this issue yourself, then feel free to make a pull request to this repository. The process for handling pull requests is described in https://github.com/bigchaindb/BEPs/tree/master/24

**Comment by tuhuynh27** [comment]
@ttmc Do you know which driver is the most stable for BigchainDB 2 now?

I think Python but how about Node.js?

**Comment by ttmc** [comment]
Python.

There were some small issues with the JS/Node.js driver available from npm. I think those were fixed in the master branch on GitHub. I think there are still some other things to do like updating some package dependencies, then a new release can be published to npm.

**Comment by tuhuynh27** [comment]
@ttmc Thank you for your comment. Do you think the Java driver is good enough to use with BigchainDB 2 but not stable? 😄

Or it is possible for us to use RESTful API call to communicate with BigchainDB without a driver? 😄

**Comment by ttmc** [comment]
As far as I know, the Java driver was working fine. The current problem with the Java driver seems to be that one of the packages that it uses has disappeared from the Java packages ecosystem.

You can certainly post a transaction (JSON string) to a BigchainDB node using any standard HTTP request-sender tool (e.g. [Postman](https://www.getpostman.com/)). The tricky thing is to construct a valid BigchainDB transaction in the first place. That's 95% of what the drivers do.
